// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUY_eL2s95CCOx0znKLAXSYC8cN_al934',
    appId: '1:629276847665:web:12fb4271fd9ca10799af10',
    messagingSenderId: '629276847665',
    projectId: 'citizenship-app-6ab4b',
    authDomain: 'citizenship-app-6ab4b.firebaseapp.com',
    storageBucket: 'citizenship-app-6ab4b.firebasestorage.app',
    measurementId: 'G-88LHEXW7CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAASGejn7XjMSu-F2JRUPgTSS86MDH1XMM',
    appId: '1:629276847665:android:38e3b1aba6bbc22999af10',
    messagingSenderId: '629276847665',
    projectId: 'citizenship-app-6ab4b',
    storageBucket: 'citizenship-app-6ab4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATqeiO4I4VrSS9zlZotveEfrEnSr2jq4c',
    appId: '1:629276847665:ios:8e01267fb84a77ac99af10',
    messagingSenderId: '629276847665',
    projectId: 'citizenship-app-6ab4b',
    storageBucket: 'citizenship-app-6ab4b.firebasestorage.app',
    iosBundleId: 'com.example.citizenshipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATqeiO4I4VrSS9zlZotveEfrEnSr2jq4c',
    appId: '1:629276847665:ios:8e01267fb84a77ac99af10',
    messagingSenderId: '629276847665',
    projectId: 'citizenship-app-6ab4b',
    storageBucket: 'citizenship-app-6ab4b.firebasestorage.app',
    iosBundleId: 'com.example.citizenshipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUY_eL2s95CCOx0znKLAXSYC8cN_al934',
    appId: '1:629276847665:web:7be224eac882a02c99af10',
    messagingSenderId: '629276847665',
    projectId: 'citizenship-app-6ab4b',
    authDomain: 'citizenship-app-6ab4b.firebaseapp.com',
    storageBucket: 'citizenship-app-6ab4b.firebasestorage.app',
    measurementId: 'G-D0XVC27NDZ',
  );
}
